name: ci-golang-workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop
      - master

jobs:
  check-application:
    runs-on: ubuntu-latest # equivalente a um FROM do Dockerfile?

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # da checkout na branch do projeto para conseguir o source code.

      - name: Setup Go
        uses: actions/setup-go@v5 # setup do ambiente go
        with:
          go-version: '1.22.4'
      - run: go version

      - name: Go Test
        run: go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Go Run
        run: go run main.go

      - name: Go Build
        run: go build -v

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push:
    needs:
      - check-application
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        id: docker_build # posso pegar o resultado da action e user dentro de outro step
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: georgebaronheid/ci-fullstack:latest

